2018-11-05 10:51:40,948 ERROR: Exception on /login [GET] [in /home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/chautc/Documents/ChauTC/myblog/app/controllers/routes.py", line 46, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: login.html
2018-11-05 10:51:40,954 ERROR: Exception on /login [GET] [in /home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/chautc/Documents/ChauTC/myblog/app/controllers/routes.py", line 46, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: login.html
2018-11-05 10:51:40,960 ERROR: Exception on /login [GET] [in /home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/chautc/Documents/ChauTC/myblog/app/controllers/routes.py", line 46, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/home/chautc/Documents/ChauTC/myblog/venv/lib/python3.5/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: login.html
2018-11-05 11:13:59,841 INFO: Microblog startup [in /home/chautc/Documents/ChauTC/myblog/app/__init__.py:53]
2018-11-05 11:23:08,871 INFO: Microblog startup [in /home/chautc/Documents/ChauTC/myblog/app/__init__.py:53]
2018-11-05 11:23:17,344 INFO: Microblog startup [in /home/chautc/Documents/ChauTC/myblog/app/__init__.py:53]
2018-11-05 11:23:35,788 INFO: Microblog startup [in /home/chautc/Documents/ChauTC/myblog/app/__init__.py:53]
2018-11-05 11:23:52,809 INFO: Microblog startup [in /home/chautc/Documents/ChauTC/myblog/app/__init__.py:53]
2018-11-05 11:23:55,043 INFO: Microblog startup [in /home/chautc/Documents/ChauTC/myblog/app/__init__.py:53]
2018-11-05 11:24:04,217 INFO: Microblog startup [in /home/chautc/Documents/ChauTC/myblog/app/__init__.py:53]
2018-11-05 13:40:53,385 INFO: Microblog startup [in /home/chautc/Documents/ChauTC/myblog/app/__init__.py:53]
2018-11-05 14:31:35,992 INFO: Microblog startup [in /home/chautc/Documents/ChauTC/myblog/app/__init__.py:53]
2018-11-05 14:32:14,378 INFO: Microblog startup [in /home/chautc/Documents/ChauTC/myblog/app/__init__.py:53]
2018-11-05 14:36:13,228 INFO: Microblog startup [in /home/chautc/Documents/ChauTC/myblog/app/__init__.py:53]
2018-11-05 14:41:31,219 INFO: Microblog startup [in /home/chautc/Documents/ChauTC/myblog/app/__init__.py:53]
2018-11-05 14:41:58,102 INFO: Microblog startup [in /home/chautc/Documents/ChauTC/myblog/app/__init__.py:53]
2018-11-05 14:42:09,719 INFO: Microblog startup [in /home/chautc/Documents/ChauTC/myblog/app/__init__.py:53]
2018-11-05 14:46:54,408 INFO: Microblog startup [in /home/chautc/Documents/ChauTC/myblog/app/__init__.py:53]
2018-11-05 14:48:25,614 INFO: Microblog startup [in /home/chautc/Documents/ChauTC/myblog/app/__init__.py:53]
2018-11-05 14:53:33,397 INFO: Microblog startup [in /home/chautc/Documents/ChauTC/myblog/app/__init__.py:53]
2018-11-05 14:53:52,325 INFO: Microblog startup [in /home/chautc/Documents/ChauTC/myblog/app/__init__.py:53]
2018-11-05 14:54:17,467 INFO: Microblog startup [in /home/chautc/Documents/ChauTC/myblog/app/__init__.py:53]
